### ISSUE TITLE
ukol_baliky

### ISSUE THREAD

**Issue by VeraKlev** [VeraKlev/Python_kurz_2022#1]
https://github.com/VeraKlev/Python_kurz_2022/blob/main/baliky_2.py

Odevzdávám úkol, abych otestovala odevzdávání, ale potřebovala bych s ním poradit prosím - bez ohledu na zadaný kód balíku mi vychází buď jeden výstup stále dokola, nebo oba výstupy dohromady.

**Comment by lutydlitatova** [comment]
Ahoj Věro @VeraKlev , jsi na dobré cestě 🙂 Zkus využít dotaz pomocí klíče slovníku (v tomhle případě kód balíku) na jeho hodnotu (tady `True` nebo `False`).

Pro inspiraci:

```py
if baliky["B541X"] == True:
    print("Balík B541X byl předán kurýrovi")
else:
    print("Balík B541X nebyl předán kurýrovi")
```

A klíč nahraď vstupem od uživatele, aby program fungoval pro všechny balíky. Kdyžtak ještě napiš tady nebo na Slacku.

**Comment by VeraKlev** [comment]
Ahoj, díky za radu. Odevzdala jsem opravený úkol spolu s novým úkolem. Nejde mi to přes "commit" z VS Code, soubory se mi neobjevují v repozitáři, tak jsem je nahrála přímo v GitHubu.

**Comment by lutydlitatova** [comment]
Super :tada: , píšu bod. Jestli chceš, můžeme se na to propojení VS Code a GitHubu podívat dneska po lekci.
