### ISSUE TITLE
Ukol - regularni vyrazy

### ISSUE THREAD

**Issue by VeraKlev** [VeraKlev/Python_kurz_2022#12]
https://github.com/VeraKlev/Python_kurz_2022/blob/5a577cef54aad0a04fc1af9267b4f268aa1dd6e4/ukol_regularni_vyrazy.py

**Comment by lutydlitatova** [comment]
Ahoj, moc díky! Napadá mne jen pár drobností:

* Co se týče znaku odřádkování `\n`, jedná se o takzvaný [bílý znak](https://cs.wikipedia.org/wiki/B%C3%ADl%C3%BD_znak), nebo anglicky whitespace character. Něco jako mezera, která je reprezentovaná prázdným místem. Zkus si schválně porovnat výstupy malého programu, který vypíše prvních 100 znaků po načtení dat, pak nahradí odřádkování mezerou, a zase vypíše prvních 100 znaků:
```py
with open('posta.html', encoding='utf-8') as vstup:
  posta = vstup.read()

print("\n=== Text se zachovanim \\n: ===")
print(posta[:100])

print("\n=== Text po nahrazeni \\n: ===")
posta = posta.replace('\n'," ")
print(posta[:100])
```

* Výraz `\s{2,}` označuje dva nebo více bílých znaků. Regulární výraz, který by označil jeden nebo více bílých znaků by mohl být takhle: `\s{2,}`, nebo ještě jednodušeji pomocí pluska: `\s+`. Pokud by nám stačilo označit jednu nebo víc mezer, šlo by to zapsat znakem mezery, po které následuje `+`. Pak pro použití `re.sub` postupně zadáme regulární výraz, který označuje, co nahrazujeme, pak čím nahrazujeme, a na konec v čem nahrazujeme, tím "zcvrkneme" víc mezer do jedné:
```py
posta_nova = re.sub(' +', ' ', posta)
```
