### ISSUE TITLE
Ukol 2_staty

### ISSUE THREAD

**Issue by VeraKlev** [VeraKlev/Python_kurz_2022#2]
https://github.com/VeraKlev/Python_kurz_2022/blob/96934f9422ce21a9c779198ec7cd95815530341e/staty_sveta.py

**Comment by lutydlitatova** [comment]
Ahoj Věro, vypadá to pěkně,díky 👍  Doporučila bych opravit jen jednu drobnost (ale bod už ti napíšu):

Tím, že využíváš operátor `in`, se ptáš, jestli dotaz uživatele je podřetězcem regionu. Pár příkladů:

```python
"X" in "Africa"   # False
"ca" in "Africa"  # True
"Afr" in "Africa" # True
"A" in "Africa"   # True
```

Takže když uživatel zadá třeba jen `"A"`, dostane místo hlášky `"Neznámý region"` státy Amerik, Afriky, Asie... všech regionů, které obsahují velké A.

Nejlépe se tomu vyhneš, když použiješ operátor porovnání `==`, a tím zkontroluješ, že region, na který se ptá uživatel, je přesně stejný jako region státu:

```python
  if otazka_region == polozka['region']: 
    ...
```
