### ISSUE TITLE
Ukol_adopce zvirat

### ISSUE THREAD

**Issue by VeraKlev** [VeraKlev/Python_kurz_2022#8]
https://github.com/VeraKlev/Python_kurz_2022/blob/d4cf65e90b233bdc79f3e4799c7b51cfcf12fc73/ukol_adopce%20zvirat.py

https://github.com/VeraKlev/Python_kurz_2022/blob/d4cf65e90b233bdc79f3e4799c7b51cfcf12fc73/ukol_adopce%20bonus.py

**Comment by lutydlitatova** [comment]
Super, díky i za bonus!
