### ISSUE TITLE
Ukol_teplota v mestech

### ISSUE THREAD

**Issue by VeraKlev** [VeraKlev/Python_kurz_2022#9]
https://github.com/VeraKlev/Python_kurz_2022/blob/d4cf65e90b233bdc79f3e4799c7b51cfcf12fc73/ukol_temperature.py

**Comment by lutydlitatova** [comment]
Moc pěkné řešení, díky! Jako čistě stylistickou věc bych možná zvážila přejmenovat proměnnou `ukol` na `data`, nebo `teploty`, `mereni` ... 🙂
